instance_class: F4_1G
runtime: nodejs14
automatic_scaling:
  min_instances: 1
vpc_access_connector:
  name: projects/ncatsidg/locations/us-central/connectors/pharos-redis-connector
includes:
  - env_variables.yaml
